create table "MF"."MF"
(
    "MFID" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    "SchemeCode" bigint,
    "SchemeName" character varying(1000),
    "LoadDateTime" timestamp with time zone DEFAULT now(),
    "isinGrowth" character varying,
    "isinDivPayout" character varying,
    "isinDivReinvestment" character varying,
    external_code character varying(20),
    short_name character varying(150),
    amc_name character varying(150),
    category character varying(50),
    fund_category character varying(100),
    plan character varying(20),
    is_direct boolean,
    maturity_type character varying(30),
    launch_date date,
    lock_in_period_days integer,
    risk_rating character varying(30),
    star_rating smallint,
    star_rating_date date,
    expense_ratio numeric(10,4),
    expense_ratio_date date,
    aum_cr numeric(14,2),
    volatility numeric(14,4),
    fund_manager text,
    investment_objective text,
    scheme_doc_url character varying(500),
    tags text[],
    lump_available boolean,
    lump_min numeric(14,2),
    lump_min_additional numeric(14,2),
    sip_available boolean,
    sip_min numeric(14,2),
    sip_frequencies text[],
    redemption_allowed boolean,
    redemption_min_amount numeric(14,4),
    switch_allowed boolean,
    stp_available boolean,
    swp_available boolean,
    instant_redemption boolean,
    instant_redeem_min numeric(14,2),
    instant_redeem_max numeric(14,2),
    tax_long_term_after_days integer,
    detail_modifieddate timestamp with time zone,
    "IsActive" boolean,
    latest_nav_date date,
    CONSTRAINT "MF_pkey" PRIMARY KEY ("MFID"),
    CONSTRAINT ux_mf_schemecode UNIQUE ("SchemeCode")
);

CREATE UNIQUE INDEX ux_mf_external_code
    ON "MF"."MF" USING btree (external_code)
    WHERE external_code IS NOT NULL;
