CREATE SEQUENCE IF NOT EXISTS "MF"."MF_MFID_seq"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

ALTER SEQUENCE "MF"."MF_MFID_seq"
    OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS "MF"."MF_NAV_MFNavID_seq"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

ALTER SEQUENCE "MF"."MF_NAV_MFNavID_seq"
    OWNER TO postgres;
